# Original Code
library(caret)
library(AppliedPredictiveModeling)
library(Hmisc)

# Q2 & 3
data(concrete)
set.seed(975)
inTrain = createDataPartition(mixtures$CompressiveStrength, p = 3/4)[[1]]
training = mixtures[ inTrain,]
testing = mixtures[-inTrain,]
training$index <- 1:length(training$CompressiveStrength)

# Plot
plot(training$CompressiveStrength)

# Generate colored models
bins <- 4 # Number of bins generated by cut2
for (v in names(training[,-c(9,10)])) {
        # Convert discret variables to factor
        training[v] <- cut2(training[v], g=bins)
        
        # Generate graph for this predictor
        g <- ggplot(training, aes(x=index, y=CompressiveStrength, color=v))
        g <- g + geom_point(shape=1)
        ggsave(filename=paste(v,".jpg"),plot=g)
}



# Q2
# Data analysis

mixtures$CompressiveStrength <- cut2(mixtures$CompressiveStrength, g=10)

# Graph
g <- ggplot(y = mixtures$CompressiveStrength, x = mixtures$index)
g <- g +  geom_point(shape=1)
g

# Q3
mixtures$Superplasticizer <- log10(mixtures$Superplasticizer)
mixtures$Superplasticizer <- cut2(mixtures$Superplasticizer, g=20)
h <- ggplot(mixtures, aes(x=mixtures$Superplasticizer,))
h <- h + geom_histogram(binwidth=.5, colour="black", fill="white")
h

# Q4
set.seed(3433)
data(AlzheimerDisease)
colNames <- names(predictors)
adData = data.frame(diagnosis,predictors[grepl("^IL",colNames)])
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]

# Predict using the PCA
preProc <- preProcess(training[,-1], method = "pca", thresh = 0.8)
alzPCA  <- predict(preProc,training[,-1])
modelFit <- train(training$diagnosis ~ ., method = "glm", data = alzPCA)
testPC <- predict(preProc,testing[,-1])

confusionMatrix(testing$diagnosis,predict(modelFit,testPC))

# Q5 - Predict with and without PCA
set.seed(3433)
data(AlzheimerDisease)
adData = data.frame(diagnosis,predictors[grepl("^IL",names(predictors))])
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]

# PCA Model
ctrl = trainControl(preProcOptions = list(thresh = 0.8))
modelPCA <- train(training$diagnosis ~ ., method = "glm", 
                  preProcess = "pca",  trControl = ctrl,
                  data=training)
confPCA <- confusionMatrix(testing$diagnosis, predict(modelPCA, testing))

# Regular Model
modelREG <- train(training$diagnosis ~ ., method = "glm", data = training)
confREG <- confusionMatrix(testing$diagnosis, predict(modelREG, testing))